import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { DatabaseError } from '../db/database.js';
import { DataError } from '../db/rows.js';
import { createServerClient } from '../db/supabase.js';

export function isMain(url: string): boolean {
  return Boolean(process.argv[1] && url === pathToFileURL(resolve(process.argv[1])).href);
}

export async function configuredClient() {
  const { config } = await import('dotenv');
  config({ quiet: true });
  // Only configuration errors generated by our module are exposed, never values.
  try { return createServerClient(); }
  catch { throw new DataError('Database configuration requires valid SUPABASE_URL and SUPABASE_SECRET_KEY.'); }
}

export function reportCliError(error: unknown) {
  console.error(error instanceof DataError || error instanceof DatabaseError
    ? error.message : 'Database command failed. No request details or credentials are logged.');
  process.exitCode = 1;
}
